export const febricsMock = [
  {
    characters: ['Breathable', 'Durable', 'Soft'],
    compositions: [
      {
        component: 'Cotton',
        percentage: 40,
      },
      {
        component: 'Wool',
        percentage: 16,
      },
      {
        component: 'Silk',
        percentage: 95,
      },
      {
        component: 'Silk',
        percentage: 61,
      },
      {
        component: 'Other',
        percentage: 66,
      },
      {
        component: 'Cotton',
        percentage: 24,
      },
    ],
    userId: '65d3277dd1365d5ecd4882e9',
    title: 'Dr',
    price: 980.13,
    deliveryTime: '3-5 business days',
    excellence: 'Medium',
    warmth: 'Medium',
    weight: 'Light',
    season: 'winter',
    threadStyle: 'Smooth',
    brightness: 'Neutral',
    superShiny: true,
    material: 'other',
    tone: 'Cool',
    threadCount: '400 TC',
    opacity: 'Opaque',
    waterproof: 'true',
    stretchyText: 'High Stretch',
    stretchy: 'true',
    type: 'Fabric',
    febricTypes: 'Silk',
    threadTypes: 'Smooth',
    threadCounts: '600 TC',
    thumbnailImageUrl: '/img/febric-18.jpg',
    originalImageUrl: '/img/febric-18.jpg',
    weave: 'twill',
    version: 0,
    id: '65dca427837038853cc39a0c',
  },
  {
    characters: ['Breathable', 'Durable', 'Soft'],
    compositions: [
      {
        component: 'Cotton',
        percentage: 40,
      },
      {
        component: 'Wool',
        percentage: 16,
      },
      {
        component: 'Silk',
        percentage: 95,
      },
      {
        component: 'Silk',
        percentage: 61,
      },
      {
        component: 'Other',
        percentage: 66,
      },
      {
        component: 'Cotton',
        percentage: 24,
      },
    ],
    userId: '65d3277dd1365d5ecd4882e9',
    title: 'Dr',
    price: 980.13,
    deliveryTime: '3-5 business days',
    excellence: 'Medium',
    warmth: 'Medium',
    weight: 'Light',
    season: 'winter',
    threadStyle: 'Smooth',
    brightness: 'Neutral',
    superShiny: true,
    material: 'other',
    tone: 'Cool',
    threadCount: '400 TC',
    opacity: 'Opaque',
    waterproof: 'true',
    stretchyText: 'High Stretch',
    stretchy: 'true',
    type: 'Fabric',
    febricTypes: 'Silk',
    threadTypes: 'Smooth',
    threadCounts: '600 TC',
    thumbnailImageUrl: '/img/febric-19.jpg',
    originalImageUrl: '/img/febric-19.jpg',
    weave: 'twill',
    version: 0,
    id: '65dca427837038853cc39a0c',
  },
  {
    characters: ['Breathable', 'Durable', 'Soft'],
    compositions: [
      {
        component: 'Cotton',
        percentage: 40,
      },
      {
        component: 'Wool',
        percentage: 16,
      },
      {
        component: 'Silk',
        percentage: 95,
      },
      {
        component: 'Silk',
        percentage: 61,
      },
      {
        component: 'Other',
        percentage: 66,
      },
      {
        component: 'Cotton',
        percentage: 24,
      },
    ],
    userId: '65d3277dd1365d5ecd4882e9',
    title: 'Dr',
    price: 980.13,
    deliveryTime: '3-5 business days',
    excellence: 'Medium',
    warmth: 'Medium',
    weight: 'Light',
    season: 'winter',
    threadStyle: 'Smooth',
    brightness: 'Neutral',
    superShiny: true,
    material: 'other',
    tone: 'Cool',
    threadCount: '400 TC',
    opacity: 'Opaque',
    waterproof: 'true',
    stretchyText: 'High Stretch',
    stretchy: 'true',
    type: 'Fabric',
    febricTypes: 'Silk',
    threadTypes: 'Smooth',
    threadCounts: '600 TC',
    thumbnailImageUrl: '/img/febric-20.jpg',
    originalImageUrl: '/img/febric-20.jpg',
    weave: 'twill',
    version: 0,
    id: '65dca427837038853cc39a0c',
  },
];
